import UserModel, { User } from "@/database/model/User"
import connectDB from "@/utils/api/connectDB"
import { logoutPost } from "@/utils/client/api"
import { JwtPayload, decode } from "jsonwebtoken"
import { GetServerSideProps, NextPage } from "next"
import Head from "next/head"

const Home: NextPage = ({ data }: any) => {
  const user: User = JSON.parse(data)
  return (
    <div className="h-screen bg-zinc-800 text-gray-100">
      <Head>
        <title>{`Home | ${user.username}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>THis is home page</h1>
      <h2>{`username:- ${user.username}`}</h2>
      <h2>{`email:- ${user.email}`}</h2>
      <h2>{`user id:- ${user._id}`}</h2>
      <h2>{`role:- ${user.role}`}</h2>

      <button
        className="bg-gray-400 py-2 px-4 text-black"
        onClick={async () => {
          await logoutPost()
          window.location.reload()
        }}
      >
        Log out
      </button>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  await connectDB()
  const token = context.req.cookies.accessToken
  if (!token)
    return { redirect: { destination: "/auth/login", permanent: false } }
  const payLoad = decode(token) as JwtPayload
  const user = await UserModel.findById(payLoad.id).exec()
  return { props: { data: JSON.stringify(user) } }
}

export default Home
