import { GetServerSideProps } from "next"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>THis is home page</h1>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async context => {
  const token = context.req.cookies.accessToken
  if (!token) return { redirect: { destination: "/auth/register", permanent: false } }
  return {
    props: {},
  }
}
